### ISSUE TITLE
What is the correct response to "{"serialRtsCtsEnabled":null}"

### ISSUE THREAD

**Issue by cxq200300** [xioTechnologies/x-IMU3-Software#1]
Hi, very good GUI for AHRS applications.
I am trying to porting my own sensor to this wonderful GUI, serial connection already done, but for the {"serialRtsCtsEnabled":null} command still can't pass.

according to user manual, I write code to send back json response as： {"serialRtsCtsEnabled":false}
But I get the response on GUI like: Unable to confirm command {"serialRtsCtsEnabled":null} for Serial xx

If the response is not :  {"serialRtsCtsEnabled":false}, then what is the correct one?

**Comment by xioTechnologies** [comment]
The GUI sends `{"serialRtsCtsEnabled":null}\r\n` to the device to query the value for the device setting _Serial RTS/CTS Enabled_.  The correct response from the device is either `{"serialRtsCtsEnabled":false}\r\n` or `{"serialRtsCtsEnabled":true}\r\n`.  If the device does not respond with either of these messages then the GUI will display the error message "Unable to confirm command...".

I suggest you try sending the setting read command using the command dialog (as shown below) so that this is only message sent.  This may help you debug the issue.

![image](https://user-images.githubusercontent.com/1748389/146683225-fd4dc12e-91a6-4e07-b784-9a2e591c91cc.png)

**Comment by cxq200300** [comment]
> The GUI sends `{"serialRtsCtsEnabled":null}\r\n` to the device to query the value for the device setting _Serial RTS/CTS Enabled_. The correct response from the device is either `{"serialRtsCtsEnabled":false}\r\n` or `{"serialRtsCtsEnabled":true}\r\n`. If the device does not respond with either of these messages then the GUI will display the error message "Unable to confirm command...".
> 
> I suggest you try sending the setting read command using the command dialog (as shown below) so that this is only message sent. This may help you debug the issue.
> 
> ![image](https://user-images.githubusercontent.com/1748389/146683225-fd4dc12e-91a6-4e07-b784-9a2e591c91cc.png)

Thank you so much for reply. 
I tried the command dialog to send the same command, and it works. 
then I figure out the problem is that my sensor response is too slow, during the initial sequence, it didn't send the response back within timeout, after I change response time it works perfect. 
thanks again for this wonderful job
