### ISSUE TITLE
Feature Request: Implement a `ReadAll` settings command

### ISSUE THREAD

**Issue by Legohead259** [xioTechnologies/x-IMU3-Software#235]
I've noticed that the x-IMU3 GUI sends out all 79 `readSetting` commands on startup. Would it be easier to have the host send a single `readAll` command that has the device send all of its settings in one shot, rather than overload the device receiving buffer with requests. Then, memory usage and processing time on the device can be lowered since only a fraction of commands need to be processed. It also allows for new settings to be dynamically added without needing to implement an additional `readSetting` command on startup.

I have already added support for this in my Arduino implementation of the [xioAPI](https://github.com/Legohead259/xioAPI-Arduino/blob/fadefe4504843d71728693c563288b2e2bfd0ce9/src/xioAPI.cpp#L300)

**Comment by xioTechnologies** [comment]
A `readAll` command is not appropriate because the GUI would then be unable to detect if any of the settings failed to read.  Each settings is requested by the GUI individually so that failed reads can be detected an managed appropriately.

Processing a series of strings terminating with `\n` should be trivial for even low performance devices.  The GUI will retry failed reads so data loss due to a receive buffer overflow should be acceptable.  If you cannot fix your performance issues then I suggest you increase the number of retries in the GUI settings.

**Comment by Legohead259** [comment]
Understood. That make sense.
