### ISSUE TITLE
connection impossible after compilation

### ISSUE THREAD

**Issue by ffbboy30** [xioTechnologies/x-IMU3-Software#491]
Hello,
I've compiled with success the c# API and put the given dll in the debug directory of the c# sample.
Now the program launch without error but it is impossible to connect to my X-IM3 with "L. UsbConnection"
The COM port is listed by the sample "E. GetPortNames"
The IMU is well connected, I can use it with the GUI. If I force the COM to the value given by the GUI I don't receive any data.

Is there a tip to make the detection possible ?

Thanks

**Comment by xioTechnologies** [comment]
I just tested the [UsbConnection.cs](https://github.com/xioTechnologies/x-IMU3-Software/blob/main/Examples/CSharp/x-IMU3-Examples/Examples/UsbConnection.cs) without issue.  I had to first download the Windows MSVC files as instructed by [this README](https://github.com/xioTechnologies/x-IMU3-Software/tree/main/x-IMU3-API/Rust/target/release#readme).  I am using Visual Studio 2022.

Please can you tell me what x-IMU3 software and firmware versions you are using.  Are you able to share a video demonstrating the x-IMU3 working with the GUI but then not working with the C# example using the same COM port?

**Comment by ffbboy30** [comment]
I've downloaded the MSVC file to compile the dll.
here is a link to view the video 
[](https://streamable.com/ayvevj)

Thanks

**Comment by xioTechnologies** [comment]
Please can you tell me what x-IMU3 software and firmware versions you are using.

**Comment by ffbboy30** [comment]
All last version
firmware 2.4.0 updated today
GUI 1.5.4

**Comment by xioTechnologies** [comment]
Thank you.  It is not clear why the x-IMU3 GUI would work but the C# example would fail, especially given that the C# example is able to see COM19.

Are you able to test the equivalent C, C++, Rust, or Python example?  Please share your findings as a video again.

**Comment by ffbboy30** [comment]
tested with the usb_connection script in python and it works fine the data are updated correctly
![ScreenCapture](https://github.com/user-attachments/assets/cf6ca647-5607-4ad7-a2ac-c57b9e9b7dc0)
Here is my c# project, maybe it is corrupted or the dll is not compiled correctly.
Test it like this and with your dll
[x-IMU3-Examples.zip](https://github.com/user-attachments/files/17516365/x-IMU3-Examples.zip)

Thanks

**Comment by ffbboy30** [comment]
I thought it could also come from ID of the COM port over 10 sometime it make some trouble.
I've tested with a serial port number at 3 on another USB port . The result is the same

**Comment by xioTechnologies** [comment]
I ran your x-IMU3-Examples.exe and I get the same issue.  I do not know what the problem is with your compilation.  I suggest you clean your local repository and start from scratch.  There are only two steps:

1. Download the missing library file as instructed [here](https://github.com/xioTechnologies/x-IMU3-Software/tree/main/x-IMU3-API/Rust/target/release).  That is, download [ximu3.lib (Windows MSVC)](https://github.com/xioTechnologies/x-IMU3-Software/releases/latest/download/x-IMU3-API-x86_64-pc-windows-msvc.zip) and put these files in the local directory, `x-IMU3-Software/x-IMU3-API/Rust/target/release`
2. Open [x-IMU3-Examples.sln](https://github.com/xioTechnologies/x-IMU3-Software/blob/main/Examples/CSharp/x-IMU3-Examples/x-IMU3-Examples.sln) and click run.

**Comment by ffbboy30** [comment]
Now it works don't understand what I've missed last time.
Thanks for your help.
